AWSTemplateFormatVersion: '2010-09-09'
Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: stack_incemental_l
        ScriptLocation: s3://bdus829/stockbucketbduk1710/yamlfiles/stock_job_incremental_1.py
      Role: arn:aws:iam::430006376054:role/AWSGlueServiceRole-Uttam
      DefaultArguments:
        "--key1": "value1"
        "--key2": "value2"
      ExecutionProperty:
        MaxConcurrentRuns: 2
      MaxRetries: 0
      Name: YourGlueJobName
      Description: Your Glue Job Description
      Timeout: 10
